import connectDB from "@/server/db/connect";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: "Tech Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  connectDB();
  return (
    <html lang="en">
      <body className={"font-jost overflow-x-hidden"}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
